/**
 * Daggerheart Loot + Consumables, transcribed from the core rulebook tables. GENERATED by
 * _pdfwork/codegen.py. Most are activated/temporary (effects: []); a few permanent passives (e.g.
 * the attribute Relics) carry structured `effects` the modifier engine applies when enabled.
 */
import type { CardEffect } from './modifiers';

export interface LootDef {
  id: string;
  name: string;
  kind: 'loot' | 'consumable';
  roll: string;
  text: string;
  effects?: CardEffect[];
}

export const LOOT: LootDef[] = [
  { id: "loot-homing-compasses", name: "Homing Compasses", kind: "loot", roll: "20", text: "These two compasses point toward each other no matter how far apart they are.", effects: [] },
  { id: "loot-corrector-sprite", name: "Corrector Sprite", kind: "loot", roll: "21", text: "This tiny sprite sits in the curve of your ear canal and whispers helpful advice during combat. Once per short rest, you can gain advantage on an attack roll.", effects: [] },
  { id: "loot-gecko-gloves", name: "Gecko Gloves", kind: "loot", roll: "22", text: "You can climb up vertical surfaces and across ceilings.", effects: [] },
  { id: "loot-lorekeeper", name: "Lorekeeper", kind: "loot", roll: "23", text: "You can store the name and details of up to three hostile creatures inside this book. You gain a +1 bonus to action rolls against those creatures.", effects: [] },
  { id: "loot-vial-of-darksmoke-recipe", name: "Vial of Darksmoke Recipe", kind: "loot", roll: "24", text: "As a downtime move, you can mark a Stress to craft a Vial of Darksmoke.", effects: [] },
  { id: "loot-bloodstone", name: "Bloodstone", kind: "loot", roll: "25", text: "You can attach this stone to a weapon that doesn't already have a feature. The weapon gains the following feature.\nBrutal: When you roll the maximum value on a damage die, roll an additional damage die.", effects: [] },
  { id: "loot-greatstone", name: "Greatstone", kind: "loot", roll: "26", text: "You can attach this stone to a weapon that doesn't already have a feature. The weapon gains the following feature.\nPowerful: On a successful attack, roll an additional damage die and discard the lowest result.", effects: [] },
  { id: "loot-glider", name: "Glider", kind: "loot", roll: "27", text: "While falling, you can mark a Stress to deploy this small parachute and glide safely to the ground.", effects: [] },
  { id: "loot-ring-of-silence", name: "Ring of Silence", kind: "loot", roll: "28", text: "Spend a Hope to activate this ring. Your footsteps are silent until your next rest.", effects: [] },
  { id: "loot-calming-pendant", name: "Calming Pendant", kind: "loot", roll: "29", text: "When you would mark your last Stress, roll a d6. On a result of 5 or higher, don't mark it.", effects: [] },
  { id: "loot-dual-flask", name: "Dual Flask", kind: "loot", roll: "30", text: "This flask can hold two different liquids. You can swap between them by flipping a small switch on the flask's side.", effects: [] },
  { id: "loot-bag-of-ficklesand", name: "Bag of Ficklesand", kind: "loot", roll: "31", text: "You can convince this small bag of sand to be much heavier or lighter with a successful Presence Roll (10). Additionally, on a successful Finesse Roll (10), you can blow a bit of sand into a target's face to make them temporarily Vulnerable.", effects: [] },
  { id: "loot-ring-of-resistance", name: "Ring of Resistance", kind: "loot", roll: "32", text: "Once per long rest, you can activate this ring after a successful attack against you to halve the damage.", effects: [] },
  { id: "loot-phoenix-feather", name: "Phoenix Feather", kind: "loot", roll: "33", text: "If you have at least one Phoenix Feather on you when you fall unconscious, you gain a +1 bonus to the roll you make to determine whether you gain a scar.", effects: [] },
  { id: "loot-box-of-many-goods", name: "Box of Many Goods", kind: "loot", roll: "34", text: "Once per long rest, you can open this small box and roll a d12. On a result of 1–6, it's empty. On a result of 7–10, it contains one random common consumable. On a result of 11–12, it contains two random common consumables.", effects: [] },
  { id: "loot-airblade-charm", name: "Airblade Charm", kind: "loot", roll: "35", text: "You can attach this charm to a weapon with a Melee range. Three times per rest, you can activate the charm and attack a target within Close range.", effects: [] },
  { id: "loot-portal-seed", name: "Portal Seed", kind: "loot", roll: "36", text: "You can plant this seed in the ground to grow a portal in that spot. The portal is ready to use in 24 hours. You can use this portal to travel to any other location where you planted a portal seed. A portal can be destroyed by dealing any amount of magic damage to it.", effects: [] },
  { id: "loot-paragons-chain", name: "Paragon's Chain", kind: "loot", roll: "37", text: "As a downtime move, you can meditate on an ideal or principle you hold dear and focus your will into this chain. Once per long rest, you can spend a Hope to roll a d20 as your Hope Die for rolls that directly align with that principle.", effects: [] },
  { id: "loot-elusive-amulet", name: "Elusive Amulet", kind: "loot", roll: "38", text: "Once per long rest, you can activate this amulet to become Hidden until you move. While Hidden in this way, you remain unseen even if an adversary moves to where they would normally see you.", effects: [] },
  { id: "loot-hopekeeper-locket", name: "Hopekeeper Locket", kind: "loot", roll: "39", text: "During a long rest, if you have 6 Hope, you can spend a Hope to imbue this locket with your bountiful resolve. When you have 0 Hope, you can use the locket to immediately gain a Hope. The locket must be re-imbued before it can be used this way again.", effects: [] },
  { id: "loot-infinite-bag", name: "Infinite Bag", kind: "loot", roll: "40", text: "When you store items in this bag, they are kept in a pocket dimension that never runs out of space. You can retrieve an item at any time.", effects: [] },
  { id: "loot-stride-relic", name: "Stride Relic", kind: "loot", roll: "41", text: "You gain a +1 bonus to your Agility. You can only carry one relic.", effects: [{ target: "agility", delta: 1, note: "+1 bonus to Agility while carried" }] },
  { id: "loot-bolster-relic", name: "Bolster Relic", kind: "loot", roll: "42", text: "You gain a +1 bonus to your Strength. You can only carry one relic.", effects: [{ target: "strength", delta: 1, note: "+1 bonus to Strength while carried" }] },
  { id: "loot-control-relic", name: "Control Relic", kind: "loot", roll: "43", text: "You gain a +1 bonus to your Finesse. You can only carry one relic.", effects: [{ target: "finesse", delta: 1, note: "+1 bonus to Finesse while carried" }] },
  { id: "loot-attune-relic", name: "Attune Relic", kind: "loot", roll: "44", text: "You gain a +1 bonus to your Instinct. You can only carry one relic.", effects: [{ target: "instinct", delta: 1, note: "+1 bonus to Instinct while carried" }] },
  { id: "loot-charm-relic", name: "Charm Relic", kind: "loot", roll: "45", text: "You gain a +1 bonus to your Presence. You can only carry one relic.", effects: [{ target: "presence", delta: 1, note: "+1 bonus to Presence while carried" }] },
  { id: "loot-enlighten-relic", name: "Enlighten Relic", kind: "loot", roll: "46", text: "You gain a +1 bonus to your Knowledge. You can only carry one relic.", effects: [{ target: "knowledge", delta: 1, note: "+1 bonus to Knowledge while carried" }] },
  { id: "loot-honing-relic", name: "Honing Relic", kind: "loot", roll: "47", text: "You gain a +1 bonus to an Experience of your choice. You can only carry one relic.", effects: [] },
  { id: "loot-flickerfly-pendant", name: "Flickerfly Pendant", kind: "loot", roll: "48", text: "While you carry this pendant, your weapons with a Melee range that deal physical damage have a gossamer sheen and can attack targets within Very Close range.", effects: [] },
  { id: "loot-lakestrider-boots", name: "Lakestrider Boots", kind: "loot", roll: "49", text: "You can walk on the surface of water as if it were soft ground.", effects: [] },
  { id: "loot-clay-companion", name: "Clay Companion", kind: "loot", roll: "50", text: "When you sculpt this ball of clay into a clay animal companion, it behaves as that animal. For example, a clay spider can spin clay webs, while a clay bird can fly. The clay companion retains memory and identity across different shapes, but they can adopt new mannerisms with each form.", effects: [] },
  { id: "loot-mythic-dust-recipe", name: "Mythic Dust Recipe", kind: "loot", roll: "51", text: "As a downtime move, you can use a handful of fine gold dust to craft Mythic Dust.", effects: [] },
  { id: "loot-shard-of-memory", name: "Shard of Memory", kind: "loot", roll: "52", text: "Once per long rest, you can spend 2 Hope to recall a domain card from your vault instead of paying its Recall Cost.", effects: [] },
  { id: "loot-gem-of-alacrity", name: "Gem of Alacrity", kind: "loot", roll: "53", text: "You can attach this gem to a weapon, allowing you to use your Agility when making an attack with that weapon.", effects: [] },
  { id: "loot-gem-of-might", name: "Gem of Might", kind: "loot", roll: "54", text: "You can attach this gem to a weapon, allowing you to use your Strength when making an attack with that weapon.", effects: [] },
  { id: "loot-gem-of-precision", name: "Gem of Precision", kind: "loot", roll: "55", text: "You can attach this gem to a weapon, allowing you to use your Finesse when making an attack with that weapon.", effects: [] },
  { id: "loot-gem-of-insight", name: "Gem of Insight", kind: "loot", roll: "56", text: "You can attach this gem to a weapon, allowing you to use your Instinct when making an attack with that weapon.", effects: [] },
  { id: "loot-gem-of-audacity", name: "Gem of Audacity", kind: "loot", roll: "57", text: "You can attach this gem to a weapon, allowing you to use your Presence when making an attack with that weapon.", effects: [] },
  { id: "loot-gem-of-sagacity", name: "Gem of Sagacity", kind: "loot", roll: "58", text: "You can attach this gem to a weapon, allowing you to use your Knowledge when making an attack with that weapon.", effects: [] },
  { id: "loot-ring-of-unbreakable-resolve", name: "Ring of Unbreakable Resolve", kind: "loot", roll: "59", text: "Once per session, when the GM spends a Fear, you can spend 4 Hope to cancel the effects of that spent Fear.", effects: [] },
  { id: "loot-belt-of-unity", name: "Belt of Unity", kind: "loot", roll: "60", text: "Once per session, you can spend 5 Hope to lead a Tag Team Roll with three PCs instead of two.", effects: [] },
];

export const CONSUMABLES: LootDef[] = [
  { id: "consumable-stride-potion", name: "Stride Potion", kind: "consumable", roll: "01", text: "You gain a +1 bonus to your next Agility Roll.", effects: [] },
  { id: "consumable-bolster-potion", name: "Bolster Potion", kind: "consumable", roll: "02", text: "You gain a +1 bonus to your next Strength Roll.", effects: [] },
  { id: "consumable-control-potion", name: "Control Potion", kind: "consumable", roll: "03", text: "You gain a +1 bonus to your next Finesse Roll.", effects: [] },
  { id: "consumable-attune-potion", name: "Attune Potion", kind: "consumable", roll: "04", text: "You gain a +1 bonus to your next Instinct Roll.", effects: [] },
  { id: "consumable-charm-potion", name: "Charm Potion", kind: "consumable", roll: "05", text: "You gain a +1 bonus to your next Presence Roll.", effects: [] },
  { id: "consumable-enlighten-potion", name: "Enlighten Potion", kind: "consumable", roll: "06", text: "You gain a +1 bonus to your next Knowledge Roll.", effects: [] },
  { id: "consumable-minor-health-potion", name: "Minor Health Potion", kind: "consumable", roll: "07", text: "Clear 1d4 HP.", effects: [] },
  { id: "consumable-minor-stamina-potion", name: "Minor Stamina Potion", kind: "consumable", roll: "08", text: "Clear 1d4 Stress.", effects: [] },
  { id: "consumable-grindletooth-venom", name: "Grindletooth Venom", kind: "consumable", roll: "09", text: "You can apply this venom to a weapon that deals physical damage to add a d6 to your next damage roll with that weapon.", effects: [] },
  { id: "consumable-varik-leaves", name: "Varik Leaves", kind: "consumable", roll: "10", text: "You can eat these paired leaves to immediately gain 2 Hope.", effects: [] },
  { id: "consumable-vial-of-moondrip", name: "Vial of Moondrip", kind: "consumable", roll: "11", text: "When you drink the contents of this vial, you can see in total darkness until your next rest.", effects: [] },
  { id: "consumable-unstable-arcane-shard", name: "Unstable Arcane Shard", kind: "consumable", roll: "12", text: "You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 1d20 magic damage.", effects: [] },
  { id: "consumable-potion-of-stability", name: "Potion of Stability", kind: "consumable", roll: "13", text: "You can drink this potion to choose one additional downtime move.", effects: [] },
  { id: "consumable-improved-grindletooth-venom", name: "Improved Grindletooth Venom", kind: "consumable", roll: "14", text: "You can apply this venom to a weapon that deals physical damage to add a d8 to your next damage roll with that weapon.", effects: [] },
  { id: "consumable-morphing-clay", name: "Morphing Clay", kind: "consumable", roll: "15", text: "You can spend a Hope to use this clay, altering your face enough to make you unrecognizable until your next rest.", effects: [] },
  { id: "consumable-vial-of-darksmoke", name: "Vial of Darksmoke", kind: "consumable", roll: "16", text: "When an adversary attacks you, use this vial and roll a number of d6s equal to your Agility. Add the highest result to your Evasion against the attack.", effects: [] },
  { id: "consumable-jumping-root", name: "Jumping Root", kind: "consumable", roll: "17", text: "Eat this root to leap up to Far range once without needing to roll.", effects: [] },
  { id: "consumable-snap-powder", name: "Snap Powder", kind: "consumable", roll: "18", text: "Mark a Stress and clear a HP.", effects: [] },
  { id: "consumable-health-potion", name: "Health Potion", kind: "consumable", roll: "19", text: "Clear 1d4+1 HP.", effects: [] },
  { id: "consumable-stamina-potion", name: "Stamina Potion", kind: "consumable", roll: "20", text: "Clear 1d4+1 Stress.", effects: [] },
  { id: "consumable-armor-stitcher", name: "Armor Stitcher", kind: "consumable", roll: "21", text: "You can use this stitcher to spend any number of Hope and clear that many Armor Slots.", effects: [] },
  { id: "consumable-gill-salve", name: "Gill Salve", kind: "consumable", roll: "22", text: "You can apply this salve to your neck to breathe underwater for a number of minutes equal to your level.", effects: [] },
  { id: "consumable-replication-parchment", name: "Replication Parchment", kind: "consumable", roll: "23", text: "By touching this piece of parchment to another, you can perfectly copy the second parchment's contents. Once used, this parchment becomes mundane paper.", effects: [] },
  { id: "consumable-improved-arcane-shard", name: "Improved Arcane Shard", kind: "consumable", roll: "24", text: "You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 2d20 magic damage.", effects: [] },
  { id: "consumable-major-stride-potion", name: "Major Stride Potion", kind: "consumable", roll: "25", text: "You gain a +1 bonus to your Agility until your next rest.", effects: [] },
  { id: "consumable-major-bolster-potion", name: "Major Bolster Potion", kind: "consumable", roll: "26", text: "You gain a +1 bonus to your Strength until your next rest.", effects: [] },
  { id: "consumable-major-control-potion", name: "Major Control Potion", kind: "consumable", roll: "27", text: "You gain a +1 bonus to your Finesse until your next rest.", effects: [] },
  { id: "consumable-major-attune-potion", name: "Major Attune Potion", kind: "consumable", roll: "28", text: "You gain a +1 bonus to your Instinct until your next rest.", effects: [] },
  { id: "consumable-major-charm-potion", name: "Major Charm Potion", kind: "consumable", roll: "29", text: "You gain a +1 bonus to your Presence until your next rest.", effects: [] },
  { id: "consumable-major-enlighten-potion", name: "Major Enlighten Potion", kind: "consumable", roll: "30", text: "You gain a +1 bonus to your Knowledge until your next rest.", effects: [] },
  { id: "consumable-blood-of-the-yorgi", name: "Blood of the Yorgi", kind: "consumable", roll: "31", text: "You can drink this blood to disappear from where you are and immediately reappear at a point you can see within Very Far range.", effects: [] },
  { id: "consumable-homets-secret-potion", name: "Homet's Secret Potion", kind: "consumable", roll: "32", text: "After drinking this potion, the next successful attack you make critically succeeds.", effects: [] },
  { id: "consumable-redthorn-saliva", name: "Redthorn Saliva", kind: "consumable", roll: "33", text: "You can apply this saliva to a weapon that deals physical damage to add a d12 to your next damage roll with that weapon.", effects: [] },
  { id: "consumable-channelstone", name: "Channelstone", kind: "consumable", roll: "34", text: "You can use this stone to take a spell or grimoire from your vault, use it once, and return it to your vault.", effects: [] },
  { id: "consumable-mythic-dust", name: "Mythic Dust", kind: "consumable", roll: "35", text: "You can apply this dust to a weapon that deals magic damage to add a d12 to your next damage roll with that weapon.", effects: [] },
  { id: "consumable-acidpaste", name: "Acidpaste", kind: "consumable", roll: "36", text: "This paste eats away walls and other surfaces in bright flashes.", effects: [] },
  { id: "consumable-hopehold-flare", name: "Hopehold Flare", kind: "consumable", roll: "37", text: "When you use this flare, allies within Close range roll a d6 when they spend a Hope. On a result of 6, they gain the effect of that Hope without spending it. The flare lasts until the end of the scene.", effects: [] },
  { id: "consumable-major-arcane-shard", name: "Major Arcane Shard", kind: "consumable", roll: "38", text: "You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 4d20 magic damage.", effects: [] },
  { id: "consumable-featherbone", name: "Featherbone", kind: "consumable", roll: "39", text: "You can use this bone to control your falling speed for a number of minutes equal to your level.", effects: [] },
  { id: "consumable-circle-of-the-void", name: "Circle of the Void", kind: "consumable", roll: "40", text: "Mark a Stress to create a void that extends up to Far range. No magic can be cast inside the void, and creatures within the void are immune to magic damage.", effects: [] },
  { id: "consumable-sun-tree-sap", name: "Sun Tree Sap", kind: "consumable", roll: "41", text: "Consume this sap to roll a d6. On a result of 5–6, clear 2 HP. On a result of 2–4, clear 3 Stress. On a result of 1, see through the veil of death and return changed, gaining one scar.", effects: [] },
  { id: "consumable-dripfang-poison", name: "Dripfang Poison", kind: "consumable", roll: "42", text: "A creature who consumes this poison takes 8d10 direct magic damage.", effects: [] },
  { id: "consumable-major-health-potion", name: "Major Health Potion", kind: "consumable", roll: "43", text: "Clear 1d4+2 HP.", effects: [] },
  { id: "consumable-major-stamina-potion", name: "Major Stamina Potion", kind: "consumable", roll: "44", text: "Clear 1d4+2 Stress.", effects: [] },
  { id: "consumable-ogre-musk", name: "Ogre Musk", kind: "consumable", roll: "45", text: "You can use this musk to prevent anyone from tracking you by mundane or magical means until your next rest.", effects: [] },
  { id: "consumable-wingsprout", name: "Wingsprout", kind: "consumable", roll: "46", text: "You gain magic wings that allow you to fly for a number of minutes equal to your level.", effects: [] },
  { id: "consumable-jar-of-lost-voices", name: "Jar of Lost Voices", kind: "consumable", roll: "47", text: "You can open this jar to release a deafening echo of voices for a number of minutes equal to your Instinct. Creatures within Far range unprepared for the sound take 6d8 magic damage.", effects: [] },
  { id: "consumable-dragonbloom-tea", name: "Dragonbloom Tea", kind: "consumable", roll: "48", text: "You can drink this tea to unleash a fiery breath attack. Make an Instinct Roll against all adversaries in front of you within Close range. Targets you succeed against take d20 physical damage using your Proficiency.", effects: [] },
  { id: "consumable-bridge-seed", name: "Bridge Seed", kind: "consumable", roll: "49", text: "Thick vines grow from your location to a point of your choice within Far range, allowing you to climb up or across them. The vines dissipate on your next short rest.", effects: [] },
  { id: "consumable-sleeping-sap", name: "Sleeping Sap", kind: "consumable", roll: "50", text: "You can drink this potion to fall asleep for a full night's rest. You clear all Stress upon waking.", effects: [] },
  { id: "consumable-feast-of-xuria", name: "Feast of Xuria", kind: "consumable", roll: "51", text: "You can eat this meal to clear all HP and Stress and gain 1d4 Hope.", effects: [] },
  { id: "consumable-bonding-honey", name: "Bonding Honey", kind: "consumable", roll: "52", text: "This honey can be used to glue two objects together permanently.", effects: [] },
  { id: "consumable-shrinking-potion", name: "Shrinking Potion", kind: "consumable", roll: "53", text: "You can drink this potion to halve your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Agility and a −1 penalty to your Proficiency.", effects: [] },
  { id: "consumable-growing-potion", name: "Growing Potion", kind: "consumable", roll: "54", text: "You can drink this potion to double your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Strength and a +1 bonus to your Proficiency.", effects: [] },
  { id: "consumable-knowledge-stone", name: "Knowledge Stone", kind: "consumable", roll: "55", text: "If you die while holding this stone, an ally can take a card from your loadout to place in their loadout or vault. After they take this knowledge, the stone crumbles.", effects: [] },
  { id: "consumable-sweet-moss", name: "Sweet Moss", kind: "consumable", roll: "56", text: "You can consume this moss during a rest to clear 1d4 HP or 1d4 Stress.", effects: [] },
  { id: "consumable-blinding-orb", name: "Blinding Orb", kind: "consumable", roll: "57", text: "You can activate this orb to create a flash of bright light. All targets within Close range become Vulnerable until they mark HP.", effects: [] },
  { id: "consumable-death-tea", name: "Death Tea", kind: "consumable", roll: "58", text: "After you drink this tea, you instantly kill your target when you critically succeed on an attack. If you don't critically succeed on an attack before your next long rest, you die.", effects: [] },
  { id: "consumable-mirror-of-marigold", name: "Mirror of Marigold", kind: "consumable", roll: "59", text: "When you take damage, you can spend a Hope to negate that damage, after which the mirror shatters.", effects: [] },
  { id: "consumable-stardrop", name: "Stardrop", kind: "consumable", roll: "60", text: "You can use this stardrop to summon a hailstorm of comets that deals 8d20 physical damage to all targets within Very Far range.", effects: [] },
];

export const ALL_LOOT: LootDef[] = [...LOOT, ...CONSUMABLES];
export function lootById(id: string): LootDef | undefined {
  return ALL_LOOT.find((x) => x.id === id);
}
