/**
 * Expo config plugin (v0.10.1) — wires react-native-hce's Host Card Emulation into the Android
 * manifest so RuneKeep can EMULATE an NFC Type-4 NDEF tag (the "send" half of NFC tap-to-share).
 * react-native-hce ships an empty library manifest, and our `android/` is regenerated by `expo
 * prebuild`, so this must be injected at prebuild time (never hand-edited into the manifest).
 *
 * Adds: the `android.hardware.nfc.hce` feature (required=false so non-NFC phones can still install),
 * the CardService HOST_APDU_SERVICE service, and the `res/xml/aid_list.xml` resource it points at.
 * The AID is the NFC Forum Type-4 well-known AID (D2760000850101) so any NDEF reader (incl.
 * react-native-nfc-manager's Ndef tech) recognises the emulated tag. The NFC permission itself is
 * added by react-native-nfc-manager's own config plugin.
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SERVICE_NAME = 'com.reactnativehce.services.CardService';

const AID_XML = `<?xml version="1.0" encoding="utf-8"?>
<host-apdu-service xmlns:android="http://schemas.android.com/apk/res/android"
                   android:description="@string/app_name"
                   android:requireDeviceUnlock="false">
  <aid-group android:category="other"
             android:description="@string/app_name">
    <aid-filter android:name="D2760000850101" />
  </aid-group>
</host-apdu-service>
`;

function addFeature(manifest) {
  manifest['uses-feature'] = manifest['uses-feature'] || [];
  if (!manifest['uses-feature'].some((f) => f.$?.['android:name'] === 'android.hardware.nfc.hce')) {
    manifest['uses-feature'].push({ $: { 'android:name': 'android.hardware.nfc.hce', 'android:required': 'false' } });
  }
}

function addService(manifest) {
  const app = manifest.application?.[0];
  if (!app) return;
  app.service = app.service || [];
  if (app.service.some((s) => s.$?.['android:name'] === SERVICE_NAME)) return;
  app.service.push({
    $: {
      'android:name': SERVICE_NAME,
      'android:exported': 'true',
      'android:enabled': 'false',
      'android:permission': 'android.permission.BIND_NFC_SERVICE',
    },
    'intent-filter': [
      {
        action: [{ $: { 'android:name': 'android.nfc.cardemulation.action.HOST_APDU_SERVICE' } }],
        category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
      },
    ],
    'meta-data': [{ $: { 'android:name': 'android.nfc.cardemulation.host_apdu_service', 'android:resource': '@xml/aid_list' } }],
  });
}

const withNfcHce = (config) => {
  config = withAndroidManifest(config, (c) => {
    addFeature(c.modResults.manifest);
    addService(c.modResults.manifest);
    return c;
  });
  config = withDangerousMod(config, [
    'android',
    (c) => {
      const xmlDir = path.join(c.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, 'aid_list.xml'), AID_XML);
      return c;
    },
  ]);
  return config;
};

module.exports = withNfcHce;
