"""
Sample every bundled card's art down to ONE colour, so the sheet can sort a hand by colour.

v0.38 (owner): "sort by color" has to work on the cards a player actually holds, and most of those
are printed scans -- domain cards, ancestries, communities, subclasses, transformations. A phone
cannot read pixels out of a bundled image at runtime (there is no pixel API in React Native, and
adding one for a sort would be a native dependency for a cosmetic feature), so the reading is done
here, once, and the answer is compiled in.

What "one colour" means, in order of what mattered:

  * The ART, not the card. Every card in this set is roughly the top half art and the bottom half
    parchment with the rules text. Averaging the whole card would return "cream" for all 363 of them.
    Only the top ART_FRACTION is read.
  * The FRAME is skipped. Each scan carries a border, so a margin is trimmed from every side before
    anything is counted.
  * Near-white and near-black pixels are dropped. Parchment bleed, the gold filigree's highlights and
    the deep shadow behind a figure are all present in every card and say nothing about which card it
    is; counting them pulls every average toward the same grey.
  * The average is taken in a way that keeps SATURATION. A plain mean of two opposite hues is grey,
    which is exactly the wrong answer for a colour sort. Hue is averaged as a unit vector (so red and
    magenta average to red-magenta rather than to cyan), and saturation and value are averaged
    straight.

Run:  python scripts/card_art_colors.py
Writes: src/data/art-colors.ts
"""

from __future__ import annotations

import colorsys
import io
import math
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / 'src' / 'data' / 'catalog.ts'
OUT = ROOT / 'src' / 'data' / 'art-colors.ts'

ART_FRACTION = 0.52   # the top of a card is its art; below that is the parchment and the rules text
MARGIN = 0.06         # trim the printed frame off every side first
WHITE_V, WHITE_S = 0.88, 0.16   # parchment / paper highlight
BLACK_V = 0.14                  # shadow


def art_color(path: Path) -> str | None:
    try:
        im = Image.open(path).convert('RGB')
    except Exception:
        return None
    w, h = im.size
    if w < 8 or h < 8:
        return None
    box = (int(w * MARGIN), int(h * MARGIN), int(w * (1 - MARGIN)), int(h * ART_FRACTION))
    im = im.crop(box)
    # A 32px-wide thumbnail is plenty: this is an average, and reading 300x400 pixels 363 times for
    # the same answer is a minute of nothing.
    im.thumbnail((32, 32))
    xs = ys = sat = val = 0.0
    n = 0
    for r, g, b in im.getdata():
        hh, ss, vv = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
        if vv < BLACK_V:
            continue
        if vv > WHITE_V and ss < WHITE_S:
            continue
        a = hh * 2 * math.pi
        xs += math.cos(a) * ss
        ys += math.sin(a) * ss
        sat += ss
        val += vv
        n += 1
    if n == 0:
        return None
    ang = math.atan2(ys / n, xs / n)
    hue = (ang / (2 * math.pi)) % 1.0
    r, g, b = colorsys.hsv_to_rgb(hue, min(1.0, sat / n), min(1.0, val / n))
    return '#%02X%02X%02X' % (round(r * 255), round(g * 255), round(b * 255))


def main() -> None:
    src = io.open(CATALOG, encoding='utf-8', newline='').read()
    # Every catalog row names its id and the file its thumbnail is required from; that is the whole
    # mapping, and reading it from the generated catalog means this can never drift out of step with it.
    rows = re.findall(r"\{ id: '([^']+)'.*?thumb: require\('([^']+)'\)", src)
    out: dict[str, str] = {}
    missing: list[str] = []
    for cid, rel in rows:
        p = (ROOT / 'src' / 'data' / rel).resolve()
        c = art_color(p) if p.exists() else None
        if c:
            out[cid] = c
        else:
            missing.append(cid)

    lines = [
        '// GENERATED by scripts/card_art_colors.py. Do not edit by hand.',
        '//',
        "// One colour per bundled card, sampled from its ART (the top half), with the printed frame,",
        '// the parchment and the shadows left out. The sheet sorts a hand by colour with these; see the',
        '// script for why the average is taken in hue-space rather than in RGB.',
        '',
        'export const ART_COLORS: Record<string, string> = {',
    ]
    for cid in sorted(out):
        lines.append("  '%s': '%s'," % (cid, out[cid]))
    lines.append('};')
    lines.append('')
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    print('art colours written: %d (%d without art)' % (len(out), len(missing)))
    if missing[:5]:
        print('  no art for:', ', '.join(missing[:5]))


if __name__ == '__main__':
    main()
