/**
 * Generate the forged-card cache signature (v0.27.4).
 *
 * A forged card is a bitmap of a component rendered from bundled data. It has to be re-captured when
 * either of those changes, and it must NOT be re-captured otherwise, because re-capturing a
 * character's whole deck costs dozens of screen-sized PNG encodes on the device's UI thread.
 *
 * v0.24.0 keyed the cache on the APP VERSION, for a good reason: the hand-maintained layout number
 * kept getting forgotten, and a forgotten bump is invisible to whoever forgot it (their device has
 * no cache for the card they just changed, so it looks right, while every existing install serves a
 * picture of the old card forever). Keying on the release made invalidation a thing that could not
 * be forgotten.
 *
 * It also made it a thing that happens on EVERY release, including the ones that only touch a screen
 * or a bug fix. That is the single largest reason the app feels slower on a phone than in a browser,
 * where nothing is ever forged at all.
 *
 * So: hash the things a card is actually made of. A release that changes a card's renderer or its
 * data gets a new signature and re-forges, which is correct. A release that changes anything else
 * keeps the cache, which is also correct. Nothing to remember, because `forge-hash.test.ts` fails
 * when the committed signature does not match the sources.
 *
 *   node scripts/forge-hash.mjs          # rewrite the constant
 *   node scripts/forge-hash.mjs --check  # exit 1 if it is out of date
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src', 'features', 'create', 'components', 'forge-hash.ts');

/**
 * Everything a captured bitmap depends on.
 *
 * Be GENEROUS here. A file left out means a card whose picture never updates, which is the worst
 * failure this cache has; a file wrongly included only costs one extra re-forge on a release that
 * touched it. `src/data` is included whole because every card's text comes from there.
 */
const SOURCES = [
  'src/data',
  'src/constants/theme.ts',
  'src/constants/identity.ts',
  'src/features/create/components/forged-card.tsx',
  'src/features/create/components/library-forged-card.tsx',
  'src/features/create/components/class-cards.tsx',
  'src/features/create/components/card-divider.tsx',
  'src/features/create/components/gold-card.tsx',
  'src/features/create/components/chamfered-image.tsx',
  'src/lib/card-markdown.ts',
];

/** Every file under a path, sorted, so the hash never depends on directory order. */
function walk(abs) {
  if (!statSync(abs).isDirectory()) return [abs];
  return readdirSync(abs)
    .sort()
    .flatMap((name) => walk(join(abs, name)));
}

export function computeHash() {
  const h = createHash('sha1');
  for (const entry of SOURCES) {
    for (const file of walk(join(ROOT, entry))) {
      // The path goes in as well as the contents, so a rename counts as a change.
      h.update(relative(ROOT, file).replace(/\\/g, '/'));
      h.update(readFileSync(file));
    }
  }
  return h.digest('hex').slice(0, 12);
}

export function currentHash() {
  const m = /FORGE_CONTENT_HASH = '([^']+)'/.exec(readFileSync(OUT, 'utf8'));
  return m ? m[1] : null;
}

const FILE = (hash) => `// GENERATED by scripts/forge-hash.mjs. Do not edit by hand.
//
// A signature of every source a forged card bitmap is rendered from: the card components, the
// palette, and all of src/data. It changes when a card's appearance or text changes, and only then,
// so an ordinary release keeps every cached bitmap instead of re-capturing the lot on the device.
// forge-hash.test.ts fails if this is out of date, so it cannot be forgotten.
export const FORGE_CONTENT_HASH = '${hash}';
`;

if (process.argv[1] && process.argv[1].endsWith('forge-hash.mjs')) {
  const next = computeHash();
  if (process.argv.includes('--check')) {
    const now = currentHash();
    if (now === next) {
      console.log(`forge hash up to date (${next})`);
    } else {
      console.error(`forge hash is STALE: committed ${now}, sources hash to ${next}`);
      console.error('Run: node scripts/forge-hash.mjs');
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, FILE(next));
    console.log(`forge hash written: ${next}`);
  }
}
