"""Generate src/features/cards/catalog.ts — static requires + metadata for every card.

Metro can only bundle literal require() paths, so the catalog must be generated, not globbed at
runtime. Re-run whenever cards are added/renamed. Reads the asset tree, derives metadata from the
ID naming scheme (see scripts/rename_cards.py), and emits one typed entry per card with its
full-res + LOD pair.

Usage:  python scripts/generate_card_catalog.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CARDS = ROOT / "assets" / "extracted_cards"
OUT = ROOT / "src" / "features" / "cards" / "catalog.ts"
REL = "../../../assets/extracted_cards"

TIER_NAMES = {1: "Foundation", 2: "Specialization", 3: "Mastery"}


def title(slug: str) -> str:
    minor = {"of", "the"}
    words = slug.split("-")
    return " ".join(w if w in minor and i else w.capitalize() for i, w in enumerate(words))


entries: list[str] = []

for dom_dir in sorted((CARDS / "Domains").iterdir()):
    if not dom_dir.is_dir():
        continue
    for f in sorted(dom_dir.glob("*.webp")):
        if f.stem.endswith("_lod"):
            continue
        m = re.fullmatch(r"([a-z]+)-(\d\d)-(\d)", f.stem)
        assert m, f.name
        dom, level, n = m.group(1), int(m.group(2)), m.group(3)
        rel = f"{REL}/Domains/{dom_dir.name}/{f.stem}"
        entries.append(
            f"  {{ id: '{f.stem}', kind: 'domain', label: '{dom_dir.name} {level}', domain: '{dom}', level: {level},"
            f" source: require('{rel}.webp'), thumb: require('{rel}_lod.webp') }},"
        )

for f in sorted((CARDS / "Ancestry").glob("*.webp")):
    if f.stem.endswith("_lod"):
        continue
    rel = f"{REL}/Ancestry/{f.stem}"
    entries.append(
        f"  {{ id: 'ancestry-{f.stem}', kind: 'ancestry', label: '{title(f.stem)}',"
        f" source: require('{rel}.webp'), thumb: require('{rel}_lod.webp') }},"
    )

for f in sorted((CARDS / "Community").glob("*.webp")):
    if f.stem.endswith("_lod"):
        continue
    rel = f"{REL}/Community/{f.stem}"
    entries.append(
        f"  {{ id: 'community-{f.stem}', kind: 'community', label: '{title(f.stem)}',"
        f" source: require('{rel}.webp'), thumb: require('{rel}_lod.webp') }},"
    )

for cls_dir in sorted((CARDS / "Subclass").iterdir()):
    if not cls_dir.is_dir():
        continue
    for f in sorted(cls_dir.glob("*.webp")):
        if f.stem.endswith("_lod"):
            continue
        m = re.fullmatch(r"(.+)-([123])-(foundation|specialization|mastery)", f.stem)
        assert m, f.name
        sub, tier = m.group(1), int(m.group(2))
        rel = f"{REL}/Subclass/{cls_dir.name}/{f.stem}"
        entries.append(
            f"  {{ id: 'subclass-{f.stem}', kind: 'subclass', label: '{title(sub)} {TIER_NAMES[tier]}',"
            f" className: '{cls_dir.name.lower()}', subclass: '{sub}', tier: {tier},"
            f" source: require('{rel}.webp'), thumb: require('{rel}_lod.webp') }},"
        )

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "/**\n"
    " * GENERATED by scripts/generate_card_catalog.py — do not edit by hand; re-run after asset\n"
    " * changes. Every playable card with its metadata and two-LOD require pair (#78). LOD thumbs\n"
    " * are gitignored build artifacts: run `python scripts/generate_lods.py` after a fresh clone\n"
    " * or Metro fails to resolve the `thumb` requires.\n"
    " */\n"
    "import type { DomainName, ClassName } from '@/constants/identity';\n\n"
    "export type CatalogKind = 'domain' | 'ancestry' | 'community' | 'subclass';\n\n"
    "export interface CatalogCard {\n"
    "  id: string;\n"
    "  kind: CatalogKind;\n"
    "  /** Human label (gallery captions, pickers). */\n"
    "  label: string;\n"
    "  source: number;\n"
    "  thumb: number;\n"
    "  domain?: DomainName;\n"
    "  level?: number;\n"
    "  className?: ClassName;\n"
    "  subclass?: string;\n"
    "  tier?: 1 | 2 | 3;\n"
    "}\n\n"
    "export const CATALOG: CatalogCard[] = [\n" + "\n".join(entries) + "\n];\n\n"
    "const byId = new Map(CATALOG.map((c) => [c.id, c]));\n\n"
    "export function cardById(id: string): CatalogCard | undefined {\n"
    "  return byId.get(id);\n"
    "}\n",
    encoding="utf-8",
    newline="\n",
)
print(f"wrote {OUT.relative_to(ROOT)} with {len(entries)} cards")
