// GENERATED by scripts/forge-hash.mjs. Do not edit by hand.
//
// A signature of every source a forged card bitmap is rendered from: the card components, the
// palette, and all of src/data. It changes when a card's appearance or text changes, and only then,
// so an ordinary release keeps every cached bitmap instead of re-capturing the lot on the device.
// forge-hash.test.ts fails if this is out of date, so it cannot be forgotten.
export const FORGE_CONTENT_HASH = 'efc1a7da7f14';
