/**
 * Catalog card -> structured stat effects (modifier engine). GENERATED by _pdfwork/codegen.py from a
 * rulebook-text pass (ancestry) and a card-vision pass (subclass, domain). Most catalog cards grant
 * no permanent passive (spells/utility) and are simply absent here (-> no effects). Community cards
 * grant none. See src/lib/modifiers.ts and src/features/cards/card-effects.ts.
 */
import type { CardEffect } from '@/lib/modifiers';
import { VITALITY_EFFECTS } from './card-choices';

export const CATALOG_EFFECTS: Record<string, CardEffect[]> = {
  "ancestry-galapa": [{ target: "majorThreshold", dynamic: "proficiency", note: "Shell: bonus to thresholds = Proficiency" }, { target: "severeThreshold", dynamic: "proficiency", note: "Shell: bonus to thresholds = Proficiency" }],
  "ancestry-giant": [{ target: "maxHp", delta: 1, note: "Endurance: 'Gain an additional Hit Point slot at character creation.'" }],
  "ancestry-human": [{ target: "stressMax", delta: 1, note: "High Stamina: 'Gain an additional Stress slot at character creation.'" }],
  "ancestry-simiah": [{ target: "evasion", delta: 1, note: "Nimble: 'Gain a permanent +1 bonus to your Evasion at character creation.'" }],
  // v0.25.0: Vitality asks the player which two of three permanent benefits it grants, so its effects
  // live with the choice that gates them. See src/data/card-choices.ts.
  "blade-05-2": VITALITY_EFFECTS,
  // v0.25.0: Celestial Trance was a hard-coded rule in rest.ts; it is a modifier now, so homebrew can
  // grant an extra downtime move too. It rides the Elf's SECOND feature, so a mix strikes it correctly.
  "ancestry-elf": [{ target: "restMoves", delta: 1, note: "Celestial Trance: choose an additional downtime move" }],
  "blade-04-2": [{ target: "majorThreshold", delta: 2, note: "+2 to damage thresholds while wearing armor" }, { target: "severeThreshold", delta: 2, note: "+2 to damage thresholds while wearing armor" }],
  "blade-07-1": [{ target: "severeThreshold", delta: 4, note: "Blade-Touched: +4 Severe damage threshold while 4+ loadout cards are Blade-domain" }],
  "bone-01-3": [{ target: "evasion", dynamic: "halfAgility", note: "Untouchable: +half Agility to Evasion" }],
  "splendor-07-2": [{ target: "severeThreshold", delta: 3, note: "+3 Severe damage threshold while 4+ loadout cards are Splendor domain" }],
  "subclass-juggernaut-2-specialization": [{ target: "severeThreshold", delta: 3, note: "Rugged: 'Gain a permanent +3 bonus to your Severe damage threshold.' (Void)" }],
  "subclass-nightwalker-3-mastery": [{ target: "evasion", delta: 1, note: "Fleeting Shadow: permanent +1 bonus to Evasion" }],
  "subclass-school-of-war-1-foundation": [{ target: "maxHp", delta: 1, note: "Battlemage: Gain an additional Hit Point slot (permanent)." }],
  "subclass-stalwart-1-foundation": [{ target: "majorThreshold", delta: 1, note: "Unwavering: permanent +1 to damage thresholds" }, { target: "severeThreshold", delta: 1, note: "Unwavering: permanent +1 to damage thresholds" }],
  "subclass-stalwart-2-specialization": [{ target: "majorThreshold", delta: 2, note: "Unrelenting: permanent +2 to damage thresholds (own new feature)" }, { target: "severeThreshold", delta: 2, note: "Unrelenting: permanent +2 to damage thresholds (own new feature)" }],
  "subclass-stalwart-3-mastery": [{ target: "majorThreshold", delta: 3, note: "Undaunted: permanent +3 to damage thresholds (own new feature)" }, { target: "severeThreshold", delta: 3, note: "Undaunted: permanent +3 to damage thresholds (own new feature)" }],
  "subclass-vengeance-1-foundation": [{ target: "stressMax", delta: 1, note: "At Ease: gain an additional Stress slot" }],
  "subclass-winged-sentinel-3-mastery": [{ target: "severeThreshold", delta: 4, note: "Ascendant: permanent +4 to Severe damage threshold" }],
  "valor-01-1": [
    { target: "armorScore", mode: "set", dynamic: "strengthPlus3", note: "Bare Bones: base Armor Score = 3 + Strength when not wearing armor" },
    { target: "majorThreshold", mode: "set", byTier: [9, 11, 13, 15], note: "Bare Bones: base Major threshold by tier (unarmored)" },
    { target: "severeThreshold", mode: "set", byTier: [19, 24, 31, 38], note: "Bare Bones: base Severe threshold by tier (unarmored)" },
  ],
  "valor-05-1": [{ target: "armorScore", delta: 1, note: "While wearing armor, +1 Armor Score (always-on while armored)" }],
  "valor-06-2": [{ target: "severeThreshold", dynamic: "proficiency", note: "Rise Up: +Proficiency to Severe threshold" }],
  "valor-07-2": [{ target: "armorScore", delta: 1, note: "+1 Armor Score while 4+ loadout cards are Valor-domain (always-on passive)" }],
};
