/**
 * Catalog card -> structured stat effects (modifier engine). GENERATED by _pdfwork/codegen.py from a
 * rulebook-text pass (ancestry) and a card-vision pass (subclass, domain). Most catalog cards grant
 * no permanent passive (spells/utility) and are simply absent here (-> no effects). Community cards
 * grant none. See src/lib/modifiers.ts and src/features/cards/card-effects.ts.
 */
import type { CardEffect } from '@/lib/modifiers';
import { VITALITY_EFFECTS } from './card-choices';

export const CATALOG_EFFECTS: Record<string, CardEffect[]> = {
  "ancestry-galapa": [{ target: "majorThreshold", dynamic: "proficiency", note: "Shell: bonus to thresholds = Proficiency" }, { target: "severeThreshold", dynamic: "proficiency", note: "Shell: bonus to thresholds = Proficiency" }],
  "ancestry-giant": [{ target: "maxHp", delta: 1, note: "Endurance: 'Gain an additional Hit Point slot at character creation.'" }],
  "ancestry-human": [{ target: "stressMax", delta: 1, note: "High Stamina: 'Gain an additional Stress slot at character creation.'" }],
  "ancestry-simiah": [{ target: "evasion", delta: 1, note: "Nimble: 'Gain a permanent +1 bonus to your Evasion at character creation.'" }],
  // v0.25.0: Vitality asks the player which two of three permanent benefits it grants, so its effects
  // live with the choice that gates them. See src/data/card-choices.ts.
  "blade-05-2": VITALITY_EFFECTS,
  // v0.25.0: Celestial Trance was a hard-coded rule in rest.ts; it is a modifier now, so homebrew can
  // grant an extra downtime move too. It rides the Elf's SECOND feature, so a mix strikes it correctly.
  "ancestry-elf": [{ target: "restMoves", delta: 1, note: "Celestial Trance: choose an additional downtime move" }],
  "blade-04-2": [{ target: "majorThreshold", delta: 2, note: "+2 to damage thresholds while wearing armor" }, { target: "severeThreshold", delta: 2, note: "+2 to damage thresholds while wearing armor" }],
  "blade-07-1": [{ target: "severeThreshold", delta: 4, note: "Blade-Touched: +4 Severe damage threshold while 4+ loadout cards are Blade-domain" }],
  "bone-01-3": [{ target: "evasion", dynamic: "halfAgility", note: "Untouchable: +half Agility to Evasion" }],
  "splendor-07-2": [{ target: "severeThreshold", delta: 3, note: "+3 Severe damage threshold while 4+ loadout cards are Splendor domain" }],
  "subclass-juggernaut-2-specialization": [{ target: "severeThreshold", delta: 3, note: "Rugged: 'Gain a permanent +3 bonus to your Severe damage threshold.' (Void)" }],
  "subclass-nightwalker-3-mastery": [{ target: "evasion", delta: 1, note: "Fleeting Shadow: permanent +1 bonus to Evasion" }],
  "subclass-school-of-war-1-foundation": [{ target: "maxHp", delta: 1, note: "Battlemage: Gain an additional Hit Point slot (permanent)." }],
  "subclass-stalwart-1-foundation": [{ target: "majorThreshold", delta: 1, note: "Unwavering: permanent +1 to damage thresholds" }, { target: "severeThreshold", delta: 1, note: "Unwavering: permanent +1 to damage thresholds" }],
  "subclass-stalwart-2-specialization": [{ target: "majorThreshold", delta: 2, note: "Unrelenting: permanent +2 to damage thresholds (own new feature)" }, { target: "severeThreshold", delta: 2, note: "Unrelenting: permanent +2 to damage thresholds (own new feature)" }],
  "subclass-stalwart-3-mastery": [{ target: "majorThreshold", delta: 3, note: "Undaunted: permanent +3 to damage thresholds (own new feature)" }, { target: "severeThreshold", delta: 3, note: "Undaunted: permanent +3 to damage thresholds (own new feature)" }],
  "subclass-vengeance-1-foundation": [{ target: "stressMax", delta: 1, note: "At Ease: gain an additional Stress slot" }],
  "subclass-winged-sentinel-3-mastery": [{ target: "severeThreshold", delta: 4, note: "Ascendant: permanent +4 to Severe damage threshold" }],
  "valor-01-1": [
    { target: "armorScore", mode: "set", dynamic: "strengthPlus3", note: "Bare Bones: base Armor Score = 3 + Strength when not wearing armor" },
    { target: "majorThreshold", mode: "set", byTier: [9, 11, 13, 15], note: "Bare Bones: base Major threshold by tier (unarmored)" },
    { target: "severeThreshold", mode: "set", byTier: [19, 24, 31, 38], note: "Bare Bones: base Severe threshold by tier (unarmored)" },
  ],
  "valor-05-1": [{ target: "armorScore", delta: 1, note: "While wearing armor, +1 Armor Score (always-on while armored)" }],
  "valor-06-2": [{ target: "severeThreshold", dynamic: "proficiency", note: "Rise Up: +Proficiency to Severe threshold" }],
  "valor-07-2": [{ target: "armorScore", delta: 1, note: "+1 Armor Score while 4+ loadout cards are Valor-domain (always-on passive)" }],

  // ---------------------------------------------------------------------------
  // v0.32.0 — cards that were collecting a loadout slot and granting nothing.
  //
  // Each of these has a number in its rules text that the sheet can hold, and none of them had an
  // entry here, so equipping them did nothing at all. The three that are CONDITIONAL (Frenzy, Deadly
  // Focus, Shadowhunter, Full Surge) rely on the new per-card modifier Toggle: equip the card, leave
  // it muted, and switch it on for the scene it applies to. That is why they can be flat modifiers at
  // all — before the Toggle, a card that is only sometimes true had to be either always on or
  // unequipped, and neither is the truth.
  // ---------------------------------------------------------------------------

  // Bone 7. "+1 to Agility, Finesse and Instinct" while 4+ of your loadout is Bone. Unconditional
  // enough to leave live; the domain requirement is the player's to keep, like every other 4+ card
  // already in this table (blade-07-1, splendor-07-2, valor-07-2).
  "bone-07-1": [
    { target: "agility", delta: 1, note: "Bone-Touched: +1 Agility while 4+ loadout cards are Bone-domain" },
    { target: "finesse", delta: 1, note: "Bone-Touched: +1 Finesse while 4+ loadout cards are Bone-domain" },
    { target: "instinct", delta: 1, note: "Bone-Touched: +1 Instinct while 4+ loadout cards are Bone-domain" },
  ],
  // Blade 8. Frenzy: while raging you cannot use Armor Slots, and you deal +10 damage. The sheet
  // number is the Armor Score going to nothing, which is what Armor Slots are. Mute the card between
  // rages.
  "blade-08-2": [
    { target: "armorScore", delta: 0, overwrite: true, note: "Frenzy: while Frenzied you can't use Armor Slots" },
    { target: "severeThreshold", mode: "bonus", delta: 8, note: "Frenzy: +8 to your Severe damage threshold while Frenzied" },
  ],
  // Blade 4. Deadly Focus: while focused on one target, +2 to any roll against them. Proficiency is
  // the only sheet number that carries a roll bonus, so that is where it lands; mute when the focus ends.
  "blade-04-1": [{ target: "proficiency", delta: 2, note: "Deadly Focus: +2 to rolls against the target you are focused on" }],
  // Midnight 8. Shadowhunter: while cloaked in shadow, +3 Evasion. Mute when you step into the light.
  "midnight-08-1": [{ target: "evasion", delta: 3, note: "Shadowhunter: +3 Evasion while cloaked in shadow" }],
  // Valor 8. Full Surge: +2 to all character traits while surging. Mute when the surge ends.
  "valor-08-1": [
    { target: "agility", delta: 2, note: "Full Surge: +2 Agility while surging" },
    { target: "strength", delta: 2, note: "Full Surge: +2 Strength while surging" },
    { target: "finesse", delta: 2, note: "Full Surge: +2 Finesse while surging" },
    { target: "instinct", delta: 2, note: "Full Surge: +2 Instinct while surging" },
    { target: "presence", delta: 2, note: "Full Surge: +2 Presence while surging" },
    { target: "knowledge", delta: 2, note: "Full Surge: +2 Knowledge while surging" },
  ],
  // Dread 8. Eldritch Flesh: +1 Armor Score for every 2 Stress you have marked. The first card that
  // reads a resource rather than a stat, which is what the `stress` formula variable is for: it moves
  // as you play, so the sheet re-derives whenever Stress changes.
  "dread-08-2": [
    { target: "armorScore", dynamic: "formula", formula: { variable: "stress", divide: 2, floor: true }, note: "Eldritch Flesh: +1 Armor Score per 2 marked Stress" },
  ],
  // Bone 2. Ferocity: +Evasion equal to the Hit Points your target marked. Nothing on the sheet knows
  // what the enemy took, so the card ASKS: the "#" button on a focused card opens a keypad and the
  // number it stores drives this formula. Per card, never global.
  "bone-02-1": [
    { target: "evasion", dynamic: "formula", formula: { variable: "input", multiply: 1 }, note: "Ferocity: +Evasion equal to the Hit Points your target marked" },
  ],
  // Splendor 9. Overwhelming Aura: your Presence is equal to your Spellcast trait. Not a bonus, a
  // replacement, which is what `overwrite` is for.
  "splendor-09-1": [
    { target: "presence", dynamic: "formula", formula: { variable: "spellcast", multiply: 1 }, overwrite: true, note: "Overwhelming Aura: your Presence equals your Spellcast trait" },
  ],
};
